/* eslint-disable prettier/prettier */
module.exports = {
  WEB_PLATFORM: 'web',
  ABOUT_YOURSELF: 'About me',
  MY_AGE: 'My age',
  FIRST_NAME: 'First Name',
  LAST_NAME: 'Last Name',
  MOBILE_NUMBER: 'Mobile Number',
  EMAIL_ADDRESS: 'Email Address',
  GENDER: 'My Gender',
  MALE: 'Male',
  FEMALE: 'Female',
  TRANSGENDER: 'Transgender',
  CITIZENSHIP: 'Citizenship',
  SSN: 'My Social Security Number',
  SECURITY_NUMBER: 'Security Number',
  // REVIEW: 'Review',
  CONTACT_DETAILS: 'Contact',
  CURRENT_ADDRESS: 'Current Address',
  MY_CURRENT_ADDRESS: 'My Current Address',

  DATE_OF_BIRTH: 'Date Of Birth',
  HELP_TEST: 'We want to make sure you are not a figment of our imagination',
  ADDRESS_DESC: 'Promise we won’t drop by unannounced ;)',
  ADDRESS_LINE_ONE: 'Address Line 1',
  ADDRESS_LINE_TWO: 'Address Line 2',
  ZIPCODE: 'Zipcode',
  BACK: 'Back',
  NEXT: 'Next',
  AGE_ERROR: 'Please enter a valid age',
  AGE_LIMIT_ERROR: 'User must be at least 18 years of age',
  SSN_ERROR: 'Please enter Social Security Number',
  ADDRESS_ERROR: 'Please enter address in Address line 1',
  ZIPCODE_ERROR: 'Zip code field is cannot be blank',
  WELCOME: 'Welcome to',
  M2I: 'Money2India',
  RIGHT_FIT: 'Why we are the right fit',
  PRIVATE_SECTOR_BANK: 'From India’s largest Private Sector Bank',
  TRUSTED_BY_MILLION_USERS: 'Trusted by over a Million Users',
  LOYALTY_PROGRAM: 'Money2India Loyalty Program',
  SECURE_TRANSFER: 'Secure Transfers',
  EXCHANGE_RATES: 'Competitive Exchange Rates',
  SUCESSFUL_TRANSACTIONS: '+3 Billion Successful Transactions',
  ABOUT_US: 'What people say about us',
  ADD_BANK_ACCOUNT: 'Add Bank Account',
  SEND_MONEY: 'Send Money',
  MONEY_SENT: 'Initiated',
  CONFIRMATION: 'Confirmation',
  STATUS_SUCCESS: 'success',
  FLAG_YES: 'Y',
  FLAG_NA: 'NA',
  ENTER_NAME: 'Please enter name',
  ENTER_MOBILE_NO: 'Please enter mobile number',
  NAME: 'Name',
  BUTTON_TITLE: {
    INFO: 'i',
    ADD_BANK_ACCOUNT: 'Add Bank Account',
    VERIFY_BANK_ACCOUNT: 'Verify Bank Account',
    VERIFIED_SUCCESFULLY: 'Bank account verification successful',
    VERIFY_YOUR_ACCOUNT: 'Verify Your Account',
    PENDING_SUBMISSION: 'Statement Submission Pending',
    INITIATE: 'Initiate',
    CANCEL: 'Cancel',
    CLOSE_ALPHA: 'Close',
    CLOSE_SYMBOL: '   X  ',
    VERIFY_ACCOUNT: 'Verify Account  >',
    ADD: 'Add',
    BACK: 'Back',
    REVIEW: 'Review  >',
    ACCOUNT_DETAILS: 'Account Details  >',
    TRANSACTION_DETAILS: 'Transaction Details  > ',
    VIEW_DETAILS: 'View Details',
    DELETE: 'Delete',
  },
  LANDING_PAGE: {
    NOW_LOGIN_USING_YOUR_INTERNET_BANKING:
      'Now login using your internet banking login',
    STEP1: 'Step 1',
    LOGIN_TO_YOUR_ICICI_BANK:
      'Login to your ICICI Bank NRI account internet banking',
    STEP2: 'Step 2',
    GO_TO_FUNDS_TRANSFER:
      'Go to funds transfer page and click on the ‘Money2India’ option.',
    STEP3: 'Step 3',
    START_SENDING_MONEY: 'Start sending money online',
    LOGIN_TO_ICICI_BANK: 'Login to ICICI Bank',
    HOW_WOULD_YOU_LIKE_TO_LOGIN: 'How would you like to login?',
    LOGIN_USING_EMAIL_ADDRESS: 'Login using email address',
    SIMPLY_ENTER_YOUR_REGISTERED_EMAIL:
      'Simply enter your registered email and generate a password.',
    LOGIN_USING_NET_BANKING: 'Login using Net banking',
    FINISH_A_THREE_STEP:
      'Finish a 3 step process to log into ICICI Bank Money2India',
    ENTER_YOUR_ICICI_BANK:
      'Step 1: Enter your ICICI Bank NRI Account net banking details',
    GO_TO_FUNDS_TRANSFER_PAGE:
      'Step 2: Go to funds transfer page and select Money2India.',
    START_SENDING_MONEY_ONLINE: 'Step 3: Start sending money online.',
    WELCOME: 'Welcome to',
    M2I: 'Money2India',
    SEND_MONEY_FROM_ANYWHERE: 'Send money from anywhere to India',
    TRUSTED_BY_MILLIONS: 'Trusted by millions across the world',
    INSTANT_TRANSFERES_TO_INDIVIDUALS:
      'Instant transfers to individuals or businesses',
    SENDING_MONEY_FROM: 'Sending money from',
    GET_STARTED: 'Get Started',
    ARE_YOU_AN_ICICI_BANK: 'Are you an ICICI Bank NRI Account holder? ',
    CLICK_HERE: 'Click Here',
    PRIVATE_SECTOR_BANK: 'From India’s largest Private Sector Bank',
    TRUSTED_BY_MILLION_USERS: 'Trusted by over a Million Users',
    LOYALTY_PROGRAM: 'Money2India Loyalty Program',
    SECURE_TRANSFER: 'Secure Transfers',
    EXCHANGE_RATES: 'Competitive Exchange Rates',
    SUCESSFUL_TRANSACTIONS: '+3 Billion Successful Transactions',
    WHAT_PEOPLE_SAY_ABOUT_US: 'What people say about us',
    RIGHT_FIT: 'Why we are the right fit',
  },
  REASONS_FOR_TRANSFER: {
    TITLE: 'Specify reasons for transfer',
    ALMOST_DONE: 'Yay, you are almost done',
  },
  MENU_ACCOUNT_TYPE: 'MENU_ACCOUNT_TYPE',
  ACCOUNT_TYPE: [
    { key: '1', value: 'Saving' },
    { key: '2', value: 'Current / Checking' },
  ],
  SENDER_DETAILS: {
    TITLE: 'Add Your Bank Account',
    BANK_ABA_ROUTING_NUMBER: 'ABA Routing Number',
    BANK_CLEARING_CODE: 'BSB / Bank Clearing Code',
    BANK_SORT_CODE: 'Bank Sort Code',
    BANK_CLEARING_CODE_INFO:
      '6 digit number printed on the bottom of the cheque',
    BANK_ABA_ROUTING_NUMBER_INFO:
      '9 digit number printed on the bottom of the cheque',
    ERROR_MSG_EMPTY_BANK_ABA_ROUTING_NUMBER: 'Please enter bank ABA number',
    ERROR_MSG_INVALID_BANK_ABA_ROUTING_NUMBER:
      'The routing number entered is invalid. Please enter a valid number',
    REMITTER_BANK_NAME: 'Bank Name',
    ACCOUNT_NUMBER: 'Account Number',
    ERROR_MSG_EMPTY_ACCOUNT_NUMBER: 'Please enter account number',
    ERROR_MSG_INVALID_ACCOUNT_NUMBER: 'Please enter a valid account number',
    ERROR_MSG_NUMERIC: 'Account number should be numeric',
    ERROR_MSG_CORRECT_ACCOUNT_NUMBER: 'Please enter correct account number',
    ERROR_MSG_EXISTS_ACCOUNT_NUMBER: 'Account number already exists',
    CONFIRM_ACCOUNT_NUMBER: 'Confirm Account Number',
    EROOR_MSG_CONFIRM_ACCOUNT_NUMBER:
      'Account number and confirm account number do not match',
    ERROR_MSG_INVALID_CONFIRM_ACCOUNT_NUMBER:
      'Confirmed account number doesn’t match with entered account number',
    ERROR_MSG_EMPTY_CONFIRM_ACCOUNT_NUMBER:
      'Please enter confirm account number',
    ACCOUNT_TYPE: 'Account Type',
    ERROR_MSG_ACCOUNT_TYPE: 'Select account type',
    NICK_NAME: 'Nick Name',
    ERROR_BLANK_ACCOUNT_NICK_NAME: 'Please enter nick name',
    ERROR_MSG_BLANK_ACCOUNT_NICK_NAME: 'Field nick name is required',
    ERROR_MSG_BLANK_ACCOUNT_BANK_NAME: 'Field bank name is required',
    ERROR_MSG_EXISTS_ACCOUNT_NICK_NAME:
      'Entered Nick already exists. Please enter another nick name',
    MONEY_GOES_FROM: 'Oh no....here goes your money :(',
    ABA_NUMBER: 'bankABANumber',
    ACC_NUM: 'accountNumber',
    CONFIRM_ACC_NUM: 'confirmAccountNumber',
    ABA_NUMBER_LEN: 9,
    CLEARING_CODE_LEN: 6,
    ACC_NUM_LEN: 12,
    ACC_NUM_MIN_LEN: 3,
    ACC_NUM_MAX_LEN: 20,
  },
  VIEW_BREAK_UP: {
    TITLE: 'Breakup Details',
    SENDING: 'Sending:',
    YOU_SEND_IN_INR: 'You Send in INR:',
    TRANSFER_FESS: 'Transfer Fees:',
    GOODS_AND_SERVICE_TAX: 'Goods and Service Tax',
    FIXED_EXCHANGE_RATE: 'Fixed Exchange Rate:',
    PROMO_CODE_DISCOUNT: 'Promo Code Discount:',
    TOTAL_AMOUNT_PAYBLE: 'Total Amount Payable:',
    TOTAL_AMOUNT_RECEIVER_GETS: 'Receiver Gets:',
  },
  VIEW_BANK_DETAILS: {
    TITLE: 'View Bank Account Details',
    LABEL_BANK_NAME: 'Bank Name',
    LABEL_BANK_ABA_NUMBER: 'Bank Sort Code/ Routing Number',
    LABEL_ACCOUNT_STATUS: 'Account Status',
    LABEL_REG_DATE: 'Account Registration Date',
  },
  NOTE: 'Note',
  READ_MORE: 'Read More',
  READ_LESS: 'Read Less',
  SELECT_RECIPIENT: 'Select recipient',
  SELECT_SOURCE: 'Select source account',
  SELECT_RECIPIENT_AND_ACCOUNT_TITLE: 'Select Recipient & Account',
  SELECT_RECIPIENT_ACCOUNT_ERROR_MSG: 'Please select receiver',
  SELECT_SOURCE_ACCOUNT_ERROR_MSG: 'Please select an account',
  DID_YOU_KNOW_TITLE: 'Did you know',
  DID_YOU_KNOW_BODY:
    'Send money to an ICICI account holder and receive a better rate.',
  MANAGE_MY_BANK_ACCOUNTS: 'Manage My Bank Accounts',
  ACCOUNT_VERIFICATION: 'Account Verification',
  BANK_ACCOUNT_STATEMENT: 'Bank Account Statement',
  BANK_ACCOUNT_STATEMENT_VERIFICATION: 'Bank Account Statement Verification',
  BANK_ACCOUNT_STATEMNT_VERIFICATION_LINE_1:
    "To initiate the sub dollar verification process, upload your bank account statement of atleast 1 month and click 'Initiate'.",
  BANK_ACCOUNT_STATEMNT_VERIFICATION_LINE_2:
    "On successful verification of your bank account statement, the sub dollar process will initiate. To check verification status of this bank account refer to 'My Bank Accounts' section.",
  UPLOAD_REQUEST: 'Kindly upload the below mentioned document',
  UPLOAD_NOTE: 'The file can be PDF / JPG / JPEG / TIFF / PNG below 2MB',
  SUB_DOLLAR_VERIFICATION_PROCESS: 'The Sub Dollar Verification Process',
  TIMELINE_EXCLUDE:
    'Timelines excludes banking holidays as well as Saturdays and Sundays in USA and in India. ',
  BANKING_HOLIDAYS_LIST_TITLE: 'Banking Holidays list',
  KINDLY_NOTE_TITLE: 'Kindly Note :',
  KINDLY_NOTE_CONTENT:
    'Recipient may receive less due to fees charged by the recipient’s bank or foreign taxes If you provide us with an incorrect account number or bank details for the recipient, you may lose the entire amount of funds transferred. Recipient may receive less due to fees charged by the recipient’s bank or foreign taxes.',
  AGREE_ACH_AUTHORISATION: 'I agree to the ACH authorisation. ',
  ACCOUNT_VERIFICATION_SUCCESSFUL:
    'Thank you for uploading your bank account statement. On successful verification of your bank account statement the sub dollar process will be initiated.',
  DELETE_BANK_ACCOUNT: 'Delete Bank Account',
  DELETE_CONFIRM_MSG: 'Are you sure you want to delete this bank account?',
  ERROR_TERMS_AND_CONDITIONS: 'Please accept terms and conditions',
  ERROR_TERMS_AND_CONDITIONS_ACH: 'Please provide authorization to proceed',
  ERROR_TERMS_AND_CONDITIONS_SUB_DOLLAR:
    'Please provide authorization to proceed',
  ERROR_EMPTY_UPLOAD_DOCUMENT: 'Please upload bank statement',
  ERROR_INVALID_UPLOAD_DOCUMENT:
    'Please upload specified format bank statement',
  COUNTRY: 'Country',
  // amount transfer
  YOU_ARE_SENDING: 'You send',
  AMOUNT_TRANSFER_HEADING: 'How much would you like to transfer to India?',
  RECIPIENT_RECEIVES: 'Receiver gets',
  TOTAL_AMOUNT_TO_BE_PAID: 'Total Amount To Be Paid',
  INCLUDES_TAXES_SERVICE_FEE: '(incld. taxes and service fee) :',
  VIEW_BREAKUP: 'View Breakup',
  ENTER_PROMO_CODE: 'Enter Promo Code',
  APPLY_AVAIL_PROMO_CODE: 'Apply and avail promo code',
  PREMIUM: ' to pay your ICICI Prudential premium',
  MONEY_INPUT_EMPTY: 'Please enter the amount',
  MINIUM_AMOUNT_TRANSACTION:
    'The minimum transaction amount is 4500. Please enter an amount greater than 0',
  DAILY_LIMITS_EXCEED:
    'Entered amount exceeds send money through some other way',
  PROMO_CODE_EMPTY: 'Kindly enter the promo code',
  PROMO_CODE_INVALID: 'Unable to find entered promo code. Please enter valid',

  // My Rewards
  My_M2I_REWARDS: 'My M2I Rewards',
  CURRENT_TIER: 'Current Tier',
  CONGRATULATIONS: 'Congratulations! You are a Gold tier member.',
  VALIDITY: 'Validity',
  TOTAL_TRANSACTION: 'Total Transaction',
  TOTAL_AMOUNT_TRANSACTED: 'Total Amount Transacted',
  SIGN_UP: 'Sign up',
  SIGNUP: 'Sign Up',
  LOGIN: 'Login',
  ARE_YOU_ICICI_BANK_HOLDER: 'Are you an ICICI Bank NRI Account holder?',
  CLICK_HERE: 'Click Here',
  FIRST_NAME_EMPTY_ERROR: 'Please enter first name',
  FIRST_NAME_MORE_THEN_THREE_CHARACTER_ERROR:
    'First name should be minimum of 3 letters',
  FIRST_NAME_INVALID_ERROR: 'Field First Name can contain only letters',
  FIRST_NAME_MORE_THEN_20_ERROR: 'Maximum length of First Name is 20 letters',
  LAST_NAME_EMPTY_ERROR: 'Please enter last name',
  LAST_NAME_INVALID_ERROR: 'Field Last Name can contain only letters',
  LAST_NAME_MORE_THEN_THREE_CHARACTER_ERROR:
    'Last name should be minimum of 3 letters',
  LAST_NAME_MORE_THEN_20_ERROR: 'Maximum length of Last Name is 20 letters',
  EMAIL_EMPTY_ERROR: 'Please enter email address',
  FIELD_EMAIL_IS_REQUIRED: 'Field Email is required',
  EMAIL_INVALID_ERROR:
    'Only ’_’, ’-’, @ and ’.’ are allowed as special characters',
  EMAIL_INVALID_ERROR_MAX_LENGTH: 'Maximum length of Email Id is 50 letters',
  MOBILE_NUMBER_EMPTY_ERROR: 'Please enter mobile number',
  MOBILE_NUMBER_INVALID: 'Please enter valid mobile number',
  MOBILE_NUMBER_INVALID_ERROR: 'Number must contain 10 digits',
  MOBILE_NUMBER_INVALID_ERROR_STARTING_WITH_0_AND_1:
    'Number can`t begin with 0 or 1.',
  SENDING_MONEY_FROM: 'Sending money from',
  REGISTER_AS: 'Register as',
  READ_TERMS_AND_CONDITIONS: 'Read Terms and Conditions',
  AGREEING_TO_TERMS_CONDITIONS:
    'I agree to receive latest updates & marketing communication from ICICI Bank Money2India',
  NEED_HELP_GIVE_MISSCALL_ON: 'Need help? Give a missed call on',
  VERIFY_WITH_OTP: 'Verify with OTP',
  CONFIRM_WITH_OTP: 'Confirm with OTP',
  SIX_DIGIT_OTP_SENT:
    'A 6-digit OTP has been sent to the following mobile number XXXXXX',
  ENTER_SIX_DIGIT_OTP: 'Enter 6-digit OTP',
  RESEND_OTP: 'Resend OTP',
  CONFIRM: 'Submit',
  ERROR_PASSWORD_EMPTY: 'Please enter password',
  ERROR_INVALID_PASSWORD:
    'Password must be 8 or more characters with a mix of both uppercase and smallercase letter,number & symbol',
  ERROR_CONFIRM_PASSWORD_EMPTY: 'Please confirm the password',
  ERROR_PASSWORD_NOT_MATCH: 'Confirm password does not match with set password',
  OTP_VERIFIED: 'OTP Verified',
  CREATE_PASSWORD: 'Enter Password',
  CONFIRM_PASSWORD: 'Confirm Password',
  CANCEL: 'Cancel',

  DOB_ERROR: 'Please enter the DOB',
  GENDER_ERROR: 'Please select your gender',
  DOB_INCORRECT_ERROR: 'Please enter valid date',
  SSN_INCORRECT_ERROR:
    'Please enter a valid 9-digit Social Security Number (SSN)',
  ZIPCODE_INCORRECT_ERROR: 'Zip should be numeric and 5 digits’ long',

  PROGRESS_STEP_LABEL: [
    'Personal Details',
    'Recipient Details',
    'Bank Details',
  ],

  BusinessSteps: ['Business Details', 'Recipient Details', 'Bank Details'],
  customStyles: {
    stepIndicatorSize: 30,
    currentStepIndicatorSize: 40,
    separatorStrokeWidth: 1,
    currentStepStrokeWidth: 3,
    stepStrokeCurrentColor: '#e77817',
    stepStrokeWidth: 2,
    stepStrokeFinishedColor: '#e77817',
    stepStrokeUnFinishedColor: '#aaaaaa',
    separatorFinishedColor: '#e77817',
    separatorUnFinishedColor: '#aaaaaa',
    stepIndicatorFinishedColor: '#e77817',
    stepIndicatorUnFinishedColor: '#ffffff',
    stepIndicatorCurrentColor: '#e77817',
    stepIndicatorLabelFontSize: 13,
    currentStepIndicatorLabelFontSize: 16,
    stepIndicatorLabelCurrentColor: '#ffffff',
    stepIndicatorLabelFinishedColor: '#ffffff',
    stepIndicatorLabelUnFinishedColor: '#aaaaaa',
    labelColor: '#4a4a4a',

    labelSize: 18,
    currentStepLabelColor: '#4a4a4a',
    labelFontFamily: 'Arial, Helvetica, sans- serif',
  },
  VERIFIED_SUCCESFULLY: 'Bank account verification successfull',
  AUTO: 'auto',
  NONE: 'none',
  BLURR_EFFECT: 0.4,

  //  ADD Recipients
  MOBILE_NUM: 'Mobile Number',
  LANDLINE_NUM: 'Phone/Landline Number',
  RECPNT_INFO: "Recipient's Info",
  BRANCH_NAME: 'Branch Name',
  CITY_NAME: 'City Name',
  BANK_ADDRESS: 'Bank Address',
  RECP_BASIC_DETAILS: "Recipient's Basic Details",
  VALID_ADDRESS_LINE:
    "Only '-’, ‘/', ',' and ‘.’ are allowed as special characters. ",
  DEMAND_DRAFT_ALERT:
    'Demand Drafts typically take 2 to 10 days more to reach your receiver compared to electronic transfers. We recommend you to use electronic transfers. Only in cases where you are unable to provide receivers bank account details or the bank is not available in the enlisted banks for electronic transfers or you require to necessarily make a demand draft payment to the receiver.',
  ENTITY_NAME_INFOTIP: "As it appears in recipient's bank records",
  IE_CODE_INFOTIP:
    'IE Code (Import Export Code) is issued by Director General of Foreign Trade(DGFT) which act as registration number to conduct import/export in India',
  ICICI_BANK_INFOTIP:
    'Send money to an ICICI account holder and receive a better rate.',
  ADD_RECIPIENT: 'Add Recipients',
  ADD_RECIPIENT_AS: 'Add recipient as',
  RECP_DETAILS_SUMMARY: 'Recipient Details Summary',
  RECP_BANK_DETAILS: 'Recipient Bank Details',
  WHERE_YOU_WANT: 'So where do you want the money to go?',
  WHERE_SHOULD_RECEIVE: 'Where should the recipient receive the money?',
  RECP_INFO: 'Recipient Info',
  TELL_US_SOMETHING: 'Tell us something more about your friend',
  RECP_ADDRESS: 'Recipient Address',
  GEEKY_OFFICERS: 'Shhhh….we just need these details for our geeky officers',
  ACC_NUMBER: 'Account Number',
  CONF_ACC_NUMBER: 'Confirm Account Number',
  NICK_NAME: 'Account Nickname',
  ENTITY_NAME: 'Entity Name',
  COUNTRY_CODE: 'Country Code',
  IE_CODE: 'IE Code',
  IFSC_CODE: 'Enter IFSC Code',
  BANK_NAME: 'Bank Name',
  CITY: 'City',
  BRANCH: 'Branch location and IFSC',
  AREA_CODE: 'Area Code',
  PHONE_LANDLINE: 'Phone/Landline Number',
  EMAIL_ID: 'Email ID',
  ADDRESS_LINE1: 'Address Line 1',
  ADDRESS_LINE2: 'Address Line 2',
  PIN_CODE: 'Pin Code',
  STATE: 'State',
  RECP_BANK_BRANCH: 'Recipient’s Bank Branch',
  REQUIRED: 'This field is required',
  REQUIRED_ACC_NUM: 'Please enter account number',
  REQUIRED_CONF_ACC_NUM: 'Please confirm account number',
  REQUIRED_NICK_NAME: 'Field nick name is required',
  REQUIRED_ENTITY_NAME: 'Please enter entity name',
  REQUIRED_FIRST_NAME: 'Please enter first name',
  REQUIRED_LAST_NAME: 'Please enter last name',
  REQUIRED_MOBILE_NO: 'Please enter mobile number',
  REQUIRED_IFSC_CODE: 'Please enter IFSC code',
  REQUIRED_EMAIL_ID: 'Field Email is required',
  REQUIRED_ADDRESS_LINE1: 'Please enter address line 1',
  REQUIRED_ADDRESS_LINE2: 'Please enter address line 2',
  REQUIRED_PINCODE: 'Pin Code field cannot be blank',
  PINCODE_LENGTH: 'Zip code should be of 6 digits',
  REQUIRED_CITY: 'Please enter city',
  ACC_NUM_ERR_MSG: 'Please enter valid account number',
  MORE_THAN_THREE_NICKNAME: 'Nick name should be at least 3 characters',
  MORE_THAN_THREE_FIRSTNAME: 'First name should be at least 3 characters',
  MORE_THAN_THREE_ENTITYNAME: 'Entity name should be at least 3 characters',
  VALID_MOBILE: 'Number must contain 10 digits',
  VALID_NICKNAME: 'Field nick name can only contain letters or numbers',
  VALID_ENTITYNAME: 'Field entity name can only contain letters or numbers',
  MATCH_ACC_NUM: 'Confirm account number doesn’t match with account number',
  EMAIL_ERROR_MSG: 'Please enter valid email address',
  PIN_CODE_ERROR_MSG: 'Please enter valid Pin Code',
  VALID_PHONE: 'Please enter valid phone number',
  VALID_IFSC: 'Please enter valid IFSC code',
  HOW_IT_WORKS: 'How it works',
  REFER_A_FRIEND: 'Refer a friend',
  LIST_OF_HOLIDAYS: 'List of Holidays',
  FOLLOW_US_ON_FACEBOOK: 'Follow us on Facebook',
  FOLLOW_US: 'Follow us ',
  HELP: 'Help',
  FAQ: 'FAQ',
  TERMS_AND_CONDITIONS: 'Terms & Conditions',
  DISCLAIMER: 'Disclaimer',
  TRAVEL_A_LOT: 'Travel a lot?',
  GET_THE_APP: ' Get the App.',
  GOOGLE_PLAY: 'Play Store',
  APP_STORE: 'App Store',
  CONTACT_US: 'Contact Us',
  CHAT: 'Chat',
  LEGAL: 'Legal',
  PRIVACY_POLICY: 'Privacy policy ',
  ICICI_COPYRIGHT: 'ICICI Bank Money2India 2019. All rights reserved',
  ICICI_BANK: '@ ICICI Bank Money2India 2019',
  Confirm: {
    title: 'Please check the details',
    sender: 'Sender',
    custname: 'Sunil Lovevanshi',
    address1: 'Prabha Building, 60 Feet Road',
    address2: 'Ghatkopar East',
    city: 'Mumbai, Maharashtra',
    pinCode: '400077',
    phone: 'Ph: 921026315',
    bankname: 'Bank of America',
    accountno: 'A/c No. XXXXXXXX6257',
    transferAmount: 'Transfer Amount:',
    transferFees: 'Transfer Fees:',
    amountPayable: 'Amount Payable:',
    reciever: 'Receiver',
    customerName: 'Sunil Lovevanshi',
    address3: 'Prabha Building, 60 Feet Road',
    address4: 'Ghatkopar East',
    cityName: 'Mumbai, Maharashtra',
    pin: '400077',
    phoneNo: 'Ph: 921026315',
    bankname1: 'Canara Bank',
    accountno1: 'A/c No. XXXXXXXX3824',
    convertedAmount: 'Converted Amount:',
    totalToRecipient: 'Total to Recipient:',
    expectedDateOfDelivery: 'Expected Date of Delivery',
    transferAmountValue: '10,000 USD',
    transferFeesValue: '+ 4.00 USD',
    amountPayableValue: '10,004.00 USD',
    convertedAmountValue: '710,000.00 INR',
    totalToRecipientValue: '710,000.00 INR',
    dateExpected: '29 Nov 2018',
  },
  Thankyoupage: {
    usdAmount: '2,104.38 USD',
    transferInitiated: 'Transfer initiated to',
    name: 'Jiten V Gathani',
    expectedToReach: 'Expected to reach by',
    date: '29 November 2018',
    viewReciept: 'View Receipt',
    addToFav: 'Add to Favourite',
    trackingId: 'Your tracking ID is M2A12321232',
    printReciept: 'Print Reciept',
  },
  Thank_you: {
    usdAmount: '2,104.38 USD',
    transferInitiated: 'Transfer initiated to',
    name: 'Siddharth Menon',
    trackId: 'Your tracking Id is',
    trackIdValue: 'M2A12321232',
    expectedToReach: 'Expected to reach by 29 November 2018',
    printReciept: 'Print Reciept',
    addToFav: 'Add to Favourite',
    print: 'Print',
  },
  ConfirmPage: {
    Sender: 'Sender',
    Recipient: 'Recipient',
    todayDate: 'Todays date',
    senderName: 'Sender Name',
    sourceOfFunds: 'Source Of Funds',
    sourceAccount: 'Source Account',
    amountToBeSent: 'Amount to be sent (inclusive of taxes and discounts)',
    estimatedDate: 'Estimated date of delivery',
    recipientName: 'Recipient Name',
    purposeOfTransfer: 'Purpose of Money Transfer',
    recipientBankAccount: 'Recipient Bank Account',
    amountToBeRecieved: 'Amount to be recieved',
  },
  Print_Reciept: {
    deliveryDate: 'Trans. Initiation Date:',
    deliveryDateValue: '30 January 2019',
    deliveryDateEst: 'Est. Delivery Date:',
    deliveryDateEstValue: '30 January 2019',
    trackingNo: 'Tracking Number:',
    trackingNoValue: 'M2X19283760',
    purposePayment: 'Purpose of Payment:',
    purposePaymentValue: 'Purpose of Advertising',
    typeTransfer: 'Transfer Type:',
    typeTransferValue: 'Online',
    rateExchange: 'Exchange Rate:',
    rateExchangeValue: '1.00 USD = 69.16 INR',
  },
  Thankyoupage: {
    usdAmount: '2,104.38 USD',
    transferInitiated: 'Transfer initiated to',
    name: 'Jiten V Gathani',
    expectedToReach: 'Expected to reach by',
    date: '29 November 2018',
    viewReciept: 'View Receipt',
    addToFav: 'Add to Favourite',
    trackingId: 'Your tracking ID is M2A12321232',
  },

  // Recipient list page constants
  viewDetail: {
    viewRecipientDetail: 'Recipient Details',
    bankDetail: "Recipient's Bank Details",
    accountNumber: 'Account Number',
    Ifsc: 'IFSC Code',
    Nickname: 'Nickname',
    recipientInfo: "Recipient's Info",
    FullName: 'Full Name',
    Nationality: 'Nationality',
    countryCode: 'Country Code',
    mobileNumber: 'Mobile Number',
    emailAddress: 'Email Address',
    recipientAddress: "Recipient's Address",
    address1: 'Address 1',
    address2: 'Address 2',
    pincode: 'Pincode',
    city: 'City',
    state: 'State',
    country: 'Country',
  },

  TRANSACITION_TYPE: [
    { key: 'All', value: 'All' },
    { key: 'Favourite', value: 'Favourite' },
    { key: 'Recurring', value: 'Recurring' },
    { key: 'Statements', value: 'Statements' },
  ],

  thankyou: {
    transferInitiated: 'Transfer Initiated',
    moneyRecievedLocal: 'Money Received in local currency',
    currencyConversion: 'Currency converted to INR',
    moneyRecieved: 'Money received in INR',
    CreditedAmount: 'Credited to recipients bank account',
  },
  ChangePassword: {
    ENTERED_PASSWORD_DOES_NOT_MATCH:
      'Entered password does not match the current paassword',
    PLEASE_CHOOSE_ANOTHER_PASSWORD:
      'New password cannot be same as old passowrd. Please choose new password',
    CHANGE_PASSWORD: 'Change Password',
    CURRENT_PASSWORD: 'Current Password',
    NEW_PASSWORD: 'New Password',
    CONFIRM_NEW_PASSWORD: 'Confirm New Password',
    ERROR_INVALID_PASSWORD_NUMBERS: 'Password must contain atleast one number',
    ERROR_INVALID_PASSWORD_SPECIAL_CHARACTERS:
      'Password must contain atleast one symbol',
    ERROR_INVALID_PASSWORD_ALPHABETS:
      'Password must contain atleast one upper case character number',
    ERROR_INVALID_PASSWORD_LENGTH: 'Password must be 8 characters long',
    PASSWORD_DOES_NOT_MATCH: 'Password does not match',
    ERROR_SHOULD_CONTAIN_UPPER_CASE:
      'Password should contain atleast one upper case character',
    // ERROR_INVALID_PASSWORD_NUMBERS:'Password should contain atleast 1 number',
    // ERROR_INVALID_PASSWORD_SPECIAL_CHARACTERS:'Password should contain atleast 1 special character',
    // ERROR_INVALID_PASSWORD_LENGTH:'Password must be 8 characters long',
    ERROR_INVALID_UPPER_CASE:
      'Password must have atleast 1 upper case character',
  },

  LogoutConstants: {
    Share_your_valuable_feedback: 'Share your valuable feedback',
    help_us_improve:
      'Help us improve your Money2India experience by taking a quick survey. Your opinion is highly valued! Thank you.',
  },
  HOW_TO_WIRE_INDIA_FROM_USA: 'How to wire money to India from USA?',
  NEW_USERS: 'New Users',
  NEW_USER: ' New user? ',
  TO_ENTER_THE_REQUIRED_DETAILS:
    'to enter the required details and send money to India in five easy steps.',
  EXISTING_USERS: 'Existing Users',
  ARE_YOU_M2I_USER_ALREADY: 'Are you a Money2India user already?',
  TO_START_SENDING_MONEY_IN_4_STEPS:
    'to start sending money in four easy steps.',
  NRI_USERS: 'NRI Users',
  TO_NRI_INTERNET_BANKING_IN_5_STEPS:
    'to NRI Internet Banking and send money in 5 easy steps.',
  YOU_CAN_ALSO_TRANSFER_MONEY_TO_INDIA:
    'You can also transfer money to India from UK, Canada, Hong Kong, Australia, UAE, and Singapore.',
  BEST_TIME_TO_SEND_M2I: 'Best time to send money to India',
  TRANSFERRING_MONEY_ONLINE:
    'Four Things to consider before transferring money online',
  BEFORE_SENDING_M2I: 'Four things to know before sending money to India',
  ERROE_MSG_EMPTY_OTP: 'OTP fields cannot be blank',
  ERROR_MSG_INVALID_OTP:
    'OTP not verified. Please enter the OTP sent to your registered mobile number',
  PLEASE_ENTER_6DIGIT_OTP:
    'Please enter the 6-digit OTP sent to your registered mobile no.',
  INFO_TIP_FIRST_NAME:
    'In case of Business please enter details of Authorized person',
  INFO_TIP_MOBILE_NUMBER:
    'Please make sure you are authorized to receive incoming short code/SMS on your mobile. One Time Password (OTP) will be shared on your mobile number via SMS.',
  INFO_TIP_EMAIL_ADDRESS:
    'This will be your Money2India login ID and will also be used to send all communications.',
  INFO_TIP_INDIVIDUAL:
    'Transfer through your personal bank account. Send money to family, friends, self or to business accounts for services availed',
  INFO_TIP_BUSINESS:
    'Transfer through your business bank account. Send payments to India based vendors or professional service providers',

  // SubDollar-Verification
  HEADER_TAG: 'Verify Bank Account Details',
  SUB_DOLLAR: 'Subdollar Verification',
  SUB_DOLLAR_CONTENT:
    'Input the two subdollar denominations of money that you have received in your bank account from ICICI Bank as part of the',
  SUB_DOLLAR_LINK_POPUP: 'subdollar verification process.',
  AMOUNT_1: 'Amount 1',
  AMOUNT_2: 'Amount 2',
  CANCEL_BTN: 'Cancel',
  CONFIRM_BTN: 'Confirm',
  NOT_EMPTY_AMOUNT_1: 'Amount 1 cannot be empty',
  NOT_EMPTY_AMOUNT_2: 'Amount 2 cannot be empty',
  ENTER_AMOUNT_1: 'Please enter amount 1',
  ENTER_AMOUNT_2: 'Please enter amount 2',

  // SubDollar-POPUP
  POPUP_HEAD: ' Subdollar Verification Process',
  TWO_DEPOSITS_POINT1:
    'ICICI Bank will make two deposits of less than 1 USD (sub - dollar) in the bank account specified by you.',
  TWO_DEPOSITS_POINT2:
    'ICICI Bank will then make one withdrawl of the above deposited money.',
  TWO_DEPOSITS_POINT3:
    'The entries will be posted into your account in 24 - 36 hrs.You will receive an email intimation from Money2India to this effect.',
  THREE_STEPS:
    'You need to follow these steps to complete the verification process',
  PROCESS_INITIATE: 'Once the Process is initiated',
  LOGIN_AFTER: 'Login after two days on the app to validate your account',
  AGREE_ACH: 'I agree to the ACH authorization. ',
  STEP_1:
    'Check your bank account statement and note the two Sub Dollar deposits(credits).',
  STEP_2:
    'Go to ‘manage my accounts’ page of Money2India to view your registered account.Click on the ‘validate account link’ against the registered account.',
  STEP_3:
    'Enter and submit the two sub-dollar deposits reflecting your bank account statement correctly & your account will be enabled for initiating transfers.',
  CLOSE_BTN: 'Close',
  VERIFICATION_BTN: 'Initiate verification',
  DISCLOSURE:
    'I confirm that I have read the E-sign Act Disclosure. I also agree that the Internet access device(s) I will use to receive the related disclosures, agreements, change notices, terms and conditions, instructions, and any other documents meet(s) the system requirements described in the disclosure presented; and I consent to receiving the related disclosures, agreements, change notices, terms and conditions, instructions, and any other documents electronically. I also confirm that I have read the',
  PRIVACY_PART_ONE:
    'and authorize ICICI Bank Money2India to verify details provided by me. I also agree to the',
  ESIGN_ACT_DISCLOSURE: ' E-sign Act Disclosure',
  // my profile
  EDIT: 'Edit',
  SAVE: 'Save',
  MY_PROFILE: 'My Profile',
  MOBILE: 'Mobile',
  EMAIL: 'Email',
  USER_ID_VALUE: 'User ID',
  SSNUM: 'Social-Security-Number',
  YES: 'Yes',
  PROFILE_INFO_SUCCESS_MSG: 'Profile Info has been updated successfully',

  // Refer Friend
  UNIQUE_CODE: 'Your unique referral code is',
  EMAIL_BLANK: 'Please enter email id',
  BETTER_RATE: 'Get better rates by referring friends to use M2I',
  BETTER_RATE_INFO:
    'Refer Money2India to a friend and receive a better rate on your next transfer once they have completed a successfull transaction.The person you have referred will receive a better rate on their first transaction as well.',
  SUCCESS_RESPONSE: 'success',
  ERROR_RESPONSE: 'error',
  SUCCESS_BOOLEAN: true,
  ERROR_BOOLEAN: false,

  expressDeliveryFeature:
    'Congratulations! You have qualified for our "Express Delivery" Feature.',
  reduceTimeFeature:
    'If you avail this feature to send money, your transaction will be completed within 2 hours.',
  selectDeliverySpeed:
    'Please select delivery speed as "Express Delivery" to avail this feature.',
  // pay bills
  YOUR_BILLERS: 'Your Billers',
  PAY_BILLS: 'Pay Bills',
  // Manage-Biller Landline
  HEAD_TAG: 'MTNL Mumbai',
  HEAD_TAG_BILLING: 'MTNL Mumbai -',
  ADD_NEW_LANDLINE: 'Add new Landline',
  TELEPHONE_NO: 'Telephone Number',
  ACCOUNT_NO: 'Account Number',
  NICKNAME: 'Nick Name',
  NEXT_BTN: 'Next',
  NOT_EMPTY_TELE_NO: 'Telephone number cannot be empty',
  NOT_EMPTY_NICKNAME: 'Nickname cannot be empty',
  NOT_EMPTY_ACC_NO: 'Account number cannot be empty',
  ENTER_TELEPHONE_NO: 'Please enter telephone number',
  ENTER_ACCOUNT_NUMBER: 'Please enter account number',
  ENTER_NICKNAME: 'Please enter nickname',
  HOME: 'Home',

  // Billing status Popup
  VIEW_BILLER: 'View Biller Details',

  // Policy details
  POLICY_HEAD: 'ICICI Prudential Life Insurance',
  ADD_POLICY: 'Add policy details',
  POLICY_DETAILS: 'Policy details',
  POLICY_NUMBER: 'Policy Number',
  POLICY_HOLDER_NAME: 'Policy Holder Name',
  ENTER_POLICY_NUMBER: 'Please enter policy number',
  ENTER_HOLDER_NAME: 'Please enter policy holder name',
  BLANK_POLICY_NUMBER: 'Policy number is required',
  BLANK_HOLDER_NAME: 'Policy holder name is required',
  // NEXT_BTN: 'Next',

  KINDLY_NOTE:
    'Recipient may receive less due to fees charged by the recipient’s bank or foreign taxes If you provide us with an incorrect account number or bank details for the recipient, you may lose the entire amount of funds transferred.',
  KINDLY_NOTE_LESS:
    'Recipient may receive less due to fees charged by the recipient’s bank or foreign taxes If you provide us with an incorrect account number or bank',
  RECIPIENT_BASIC_DETAILS: "Recipient's Basic Details",
  MY_ACCOUNT_DEATILS: 'My Account Details',
  NEW_ADD_ACCOUNT: 'NewAddAccount',
  UK_ADD_ACCOUNT: 'UkAddAccount',
  CAN_ADD_ACCOUNT: 'CanAddAccount',
  UAE_ADD_ACCOUNT: 'UaeAddAccount',
  AUS_ADD_ACCOUNT: 'AusAddAccount',
  HK_ADD_ACCOUNT: 'HkAddAccount',
  SIN_ADD_ACCOUNT: 'SinAddAccount',
  ACCOUNT_DETAILS: 'AccountDetails',
  SENDER_RECEIPT: 'SenderReceipt',
  RECIEPT: 'Receipt',
  FROM: 'from',
  BRANCH_DETAILS: 'BranchDetails',

  // TIN/EIN/FEIN
  TIN_TOOLTIP_MSG:
    'TIN: Tax Identification Number EIN: Employer Identification Number FEIN: Federal Employer Identification Number',

  // Add Recipient Validation Message
  ADD_RECIPIENT_VALIDATION: {
    FIRST_NAME: 'Please enter first name',
    FIRST_NAME_ONLY_LETTERS: 'Field First Name can contain only letters',
    FIRST_NAME_MAX_LENGTH: 'Maximum length of First Name is 20 letters',
    FIRSTNAME_LENGTH: 'First name should be at least 3 characters',
    LAST_NAME: 'Please enter last name',
    LAST_NAME_ONLY_LETTERS: 'Field Last Name can contain only letters',
    LAST_NAME_MAX_LENGTH: 'Maximum length of Last Name is 20 letters',
    // LASTNAME_LENGTH: 'Last name should be more than 3 characters',
    MOBILE_NUMBER: 'Please enter mobile number',
    VALID_MOBILE_NUMBER: 'Number must contain 10 digits',
    PHONE_NUMBER: 'Please enter phone number',
    STD_CODE: 'Please enter area code',

    VALID_US_MOBILE_NUMBER: "Number can't begin with 0 or 1",
    EMAIL_ID: 'Field Email is required',
    VALID_EMAIL_ID: `Only '_’, '-’, '@' and '.' are allowed as special characters.`,
    VALID_50_EMAIL_ID: 'Maximum length of Email Id is 50 letters',
    NICKNAME_LENGTH: 'Nickname name should be at least 3 characters',
    NICKNAME_VALID: 'Field nickname can only contain letters or number',
    ADDRESS_ONE: 'Please enter address line 1',
    ADDRESS_TWO: 'Please enter address line 2',
    VALID_ADDRESS:
      "Only ' -’, ‘/ ', ',' and ‘.’ are allowed as special characters.",
    ADDRESS_ONE_LENGTH: 'Address line 1 should be at least 3 characters',
    ADDRESS_TWO_LENGTH: 'Address line 2 should be at least 3 characters',
    PINCODE: 'Pin Code field cannot be blank',
    PINCODE_LENGTH: 'Zip code should be of 6 digits',
    ENTITY_NAME: 'Please enter entity name',
    VALID_ENTITY_NAME: 'Entity name should be at least 3 characters',
    IFSC_CODE: 'IFSC field cannot be blank',
    VALID_IFSC: 'Please enter valid IFSC code',
    SELECT_BANK_NAME: 'Please select bank name',
    SELECT_CITY_NAME: 'Please select city name',
    SELECT_BRANCH_NAME: 'Please select branch name',
    SELECT_AREA_CODE: 'Please select area code',
    SELECT_STATE_NAME: 'Please select recipient’s state of residence',
    SELECT_COUNTRY_NAME: 'Please select recipient’s country of residence',
    SELECT_CITY_ADDRESS: 'Please enter recipient’s city of residence',
    CITY: 'Please enter the city',
    CITY_LENGTH: 'City should be at least 3 characters',
  },
  // transaction details
  PURPOSE_OF_TRANSFER:
    'This is a government mandate to ensure the money you send is going to be put to good use',
  SOURCE_OF_FUND:
    'This is a government mandate to ensure the money you send is sourced legally.',
  FREQUENCY_OF_TRANSFER: 'Please select the frequency of transfer',
  ONE_TIME: 'One Time',
  RECURRING: 'Recurring',
  MAKE_TRANSACTION: 'When do you wish to make the transaction',
  SEND_NOW: 'Send Now',
  SEND_LATER: 'Send Later',
  REVIEW: 'Review  >',
  VERIFIED_ADDED_SUCCESS: 'Your account was added successfully',
  BANK_ACCOUNT_ADDED_SUCCESS: 'Your account was failed to validate',
  BANK_ACCOUNT_ADDED_FAILURE: 'Failed to create the new account',

  VERIFY_ACCOUNT: 'verify_1_',
  STAT_PENDING: 'verify_2_',
  ACTIVE: 'Account Enabled',
  VERTICAL_MENU_ICON: 'v_dots',
  FILE_ICON: 'file',
  DELETE_ICON: 'delete',

  NO_RECORDS_FOUND: 'No records found',
  NEW_ADD_RECIPIENT: 'MyRecipients',
};
