module.exports = {
  SIGNUP: 'SAVECUSTOMER',
  SIGNUP_OTP: 'Sign up otp',
  SIGNUP_OTP_VERIFY: 'Sign up otp verify',
  CURRENCY_CONVERTER: 'Currency converter',
  RECIPIENT_ADDRESS_STATE: 'recipient address state',
  RECIPIENT_ADDRESS_COUNTRY: 'recipient address country',
  PURPOSE_OF_TRANSFER: 'purpose of transfer',
  SOURCE_OF_FUND: 'source of fund',
  RECIPIENT_ADDRESS_CITIZENSHIP: 'citizenship',
  US_CITY: 'US City',
  US_STATE: 'Us State',
  COUNTRY_LIST: 'Get country list',
  STATE_LIST_FROM_COUNTRY: 'Get state list from selected country',
  INDIVIDUAL_NON_ICICI_BANKS: 'Individual non icici bank',
  INDIVIDUAL_NON_ICICI_BANK_CITY_LIST: 'Individual non icici bank city list',
  INDIVIDUAL_NON_ICICI_BANK_BRANCH_LIST:
    'Individual non icici bank city branch list',
  NEW_RECIPIENT_REQUEST: 'New recipient request list',
  LAST_FIVE_TRANSACTION: 'Last five transaction list',
  RECENT_FAV_TRANSACTION: 'Recent Favorite transaction list',
  RECIPIENT_REQUEST_COUNT: 'Recipient request count',
  FAV_TRANSACTION: 'Favorite transaction list',
  PRE_LOGIN_SERVICES: 'Pre login services',
  LOGIN_SERVICES: 'Login services',
  POST_LOGIN: 'Post Login services',

  VERIFY_BANK_ABA_NUMBER: 'Verify bank ABA number',
  MY_REGISTARTION_REFERRALS_STATUS_LIST:
    'My registration referrals status list',
  MY_TRANSACTION_REFERRALS_STATUS_LIST: 'My transaction referrals status list',
  MY_RECIPIENT_LIST: 'My recipient list',
  UPDATE_REFARRAL_ID: 'Update refarral id',
  MY_RECIPIENT_REQUEST_LIST: 'My recipient request list',
  SAVE_CONTACT_DETAILS: 'Save contact details',
  MY_BANK_ACCOUNT_LIST: 'My bank account list',
  VERIFY_BANK_DETAILS: 'Verify bank details',
  VERIFY_TXN: 'Verify TXN',
  ADD_BANK_DETAILS: 'Add bank details',
  GET_PROFILE_DETAILS: 'Get profile details',
  SAVE_PROFILE_DETAILS: 'Save profile details',
  SELECT_RECIPIENT_LIST: 'Select recipient list',
  DD_PAYABLE_LIST: 'DD payable list',
  MANAGE_BILLERS: 'Manage Billers',
  ACCOUNT_DROPDOWN: 'Select account dropdown',
  ALL_TRANSACTION_LIST: 'All transaction list',
  RECURRING_TRANSACTION: 'Recurring transactions',
  ADD_REMOVE_FAVOURITE: 'Add remove favourite',
  REFERRAL_STATUS_LIST: 'Get referral status list',
  SEND_REFERRAL: 'Send referral request',
  SEND_REFERRAL_REMINDER: 'Send referral request',
  CHANGE_PASSWORD: 'Change password',
  RESET_PASSWORD: 'Reset password',
  FORGOT_PASSWORD: 'Forgot password',
  FORGOT_USERID: 'Forgot user id send otp',
  TRACK_PRE_STATUS: 'Track pre status',
  MY_BILLER_LIST: 'My biller',
  DONATION_LOCATION: 'Donation location dropdown',
  DONATION_CATEGORY: 'Donation category dropdown',
  REGISTERED_CATEGORY: 'Registered category dropdown',
  DONATION_BENEFICIARY_LIST: 'Donation beneficiary list',
  REGISTERED_ENTITY_LIST: 'Registered entity list',
  ADD_BENEFICIARY_LIST: 'Add beneficiary list',
  PREMIUM_INSURANCE: 'ICICI premium insurance',
  SAVE_DETAILS: 'save details',
  LOGOUT: 'logout',
  CONFIRM_PRE_RECURRING_TRANSACTION: 'Confirm Pre Recurring transaction',
  CONFIRM_PRE_ONE_TIME_TRANSACTION: 'Confirm Pre One Time transaction',
  CONFIRM_POST_TRANSACTION: 'Confirm Post One Time transaction',
  TransactionSendOtp: 'Transaction Send Otp',
  TransactionVerifyOtp: 'TRansaction Verify Otp',
  EXPRESS_DELIVERY: 'express delivery',
  SEND_MONEY_ACTION: 'send money action',
  PROMO_CODE: 'promo code',
  ADD_BILLERS: 'Add billers',
  ADD_LANDLINE: 'Add landline',
  SAVE_REGISTERED_BILLER: 'Save registered biller service',
  SAVE_PRESENTMENT_BILLER: 'Save presentment biller service', // ActSavePresentMentBillerService
  BILLING_STATUS_VIEW_DETAILS: 'Billing status view details',
  CONFIRM_PAY_OTP: 'Confirm Pay OTP',
  MY_REWARDS_LIST: 'My rewards list',

  VIEW_ALL_NOTIFICATIONS: 'View All notifications',
  View_Reciept: 'View Reciept',
  TRANSACTION_SEND_OTP: 'Transaction Send Otp',
  TRANSACTION_VERIFY_OTP: 'TRansaction Verify Otp',

  // add -recpient
  IFSC_CHECK: 'ifsc check',
  ADD_RECIPIENT_IND_ICICI: 'add recipient ind icici',
  ADD_RECIPIENT_IND_NONICICI: 'add recipient ind non icici',
  ADD_RECIPIENT_BUS_NONICICI: 'add recipient bus non icici',
  ADD_RECIPIENT_BUS_ICICI: 'add recipient bus icici',

  UPLOAD_DOCUMENTS: 'upload documents',
  AUTH_TOKEN: 'authorization token',
  DELETE_MY_ACCOUNTS: 'delete my accounts',
  INITIATE_MY_ACCOUNTS: 'initiate my accoutns',
  OTP_STATUS: 'OTP status',
  GET_TOKEN: 'Get Token',
  SUB_DOLLAR_VERIFICATION: 'sub dollar verification',
  APPLY_GOLD_MEMBERSHIP: 'apply gold membership',
  CSRF_TOKEN: 'csrf token',
  SSN_CHECK: 'ssn check',
  REMITTER_ACCOUNT_CHECK: 'remitter ac check',
  BENEFICIARY_ACCOUNT_CHECK: 'beneficiary ac check',
  POST_CALCULATION: 'post calculation',

  // temporary purpose
  AUTH_KEY:
    'Bearer eyJhbGciOiJIUzI1NiJ9.eyJqdGkiOiJjZTcyNmZlNC1lOTg1LTRjM2QtODAzYS1jMzYwZTAxNWQwMGMiLCJpc3MiOiJodHRwOi8vZXhhbXBsZS5vcmciLCJhdWQiOiJodHRwOi8vZXhhbXBsZS5vcmciLCJzdWIiOiJyYWplc2guc3V2YXJuYUBuaXZldXNzb2x1dGlvbnMuaW4iLCJpYXQiOjE1NzU5NzI5NzYsImV4cCI6MTU3NTk3MzI3NiwicmVmcmVzaENvdW50IjowLCJyZWZyZXNoTGltaXQiOjF9.-vJa3vYZ7UhAziOHud5oSorumXlKrMv-cc2xZV4hBNs',
};
